---
stages:
  - linting
  - build
  - build-optional

format:
  stage: linting
  image: ubuntu:24.04
  before_script:
    - apt update -qq
    - apt install -y -qq git python3-pip
    - apt install -y clang-format-14 cmake-format pre-commit
  script:
    - pre-commit run -a


include:
  - .gitlab-ci-cuda.yml
  - .gitlab-ci-rocm.yml
