name: build
on:
  push:
jobs:
  build-cuda:
    name: CUDA ${{ matrix.CUDA_IMAGE }}
    runs-on: [docker]
    strategy:
      matrix:
        CUDA_IMAGE: ["nvidia/cuda:12.8.1-devel-ubuntu24.04"]
    container: ${{ matrix.CUDA_IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y cmake git
      - run: cmake -S . -B build
      - run: make -C build -j
  build-rocm:
    name: ${{ matrix.ROCM_IMAGE }}
    runs-on: [docker]
    strategy:
      matrix:
        ROCM_IMAGE: ["rocm/dev-ubuntu-24.04:6.4"]
    container: ${{ matrix.ROCM_IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y cmake git hipfft-dev rocwmma-dev
      - run: cmake -S . -B build -DBUILD_WITH_HIP=1
      - run: make -C build -j
