name: linting
on:
  push:
jobs:
  format:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: sudo apt-get update && sudo apt-get install -y clang-format-14 cmake-format
      - run: pip install pre-commit
      - run: pre-commit run -a
