name: test-optional
on:
  workflow_dispatch:
jobs:
  test-a100:
    name: NVIDIA A100
    runs-on: [slurm]
    on: workflow_dispatch
    steps:
      - uses: actions/checkout@v4
      - uses: astron-rd/slurm-action@v1
        with:
          partition: defq
          gres: gpu:A100
          time: "00:10:00"
          commands: |
            module load spack/20250403
            module load cuda
            cmake -S . -B build -DCMAKE_CUDA_ARCHITECTURES=80
            make -C build -j
            ./build/benchmarks/fp32
            ./build/benchmarks/mma
  test-ad4000:
    name: NVIDIA AD4000
    runs-on: [slurm]
    on: workflow_dispatch
    steps:
      - uses: actions/checkout@v4
      - uses: astron-rd/slurm-action@v1
        with:
          partition: fatq
          gres: gpu:AD4000
          time: "00:10:00"
          commands: |-
            module load spack/20250403
            module load cuda
            cmake -S . -B build -DCMAKE_CUDA_ARCHITECTURES=89
            make -C build -j
            ./build/benchmarks/fp32
            ./build/benchmarks/mma
