name: test
on:
  push:
jobs:
  test-a4000:
    name: NVIDIA A4000
    runs-on: [slurm]
    steps:
      - uses: actions/checkout@v4
      - uses: astron-rd/slurm-action@v1
        with:
          partition: defq
          gres: gpu:A4000
          time: "00:10:00"
          commands: |
            BUILD_DIR=$(mktemp -d -t build-XXXXXXXX)
            module load spack/20250403
            module load cuda
            cmake -S . -B ${BUILD_DIR} -DCMAKE_CUDA_ARCHITECTURES=86
            make -C ${BUILD_DIR} -j
            ${BUILD_DIR}/benchmarks/fp32
            ${BUILD_DIR}/benchmarks/mma
  test-w7700:
    name: AMD W7700
    runs-on: [slurm]
    steps:
      - uses: actions/checkout@v4
      - uses: astron-rd/slurm-action@v1
        with:
          partition: defq
          gres: gpu:W7700
          time: "00:10:00"
          commands: |-
            BUILD_DIR=$(mktemp -d -t build-XXXXXXXX)
            cmake -S . -B ${BUILD_DIR} -DBUILD_WITH_HIP=1 -DCMAKE_HIP_ARCHITECTURES=gfx1101
            make -C ${BUILD_DIR} -j
            ${BUILD_DIR}/benchmarks/fp32
            ${BUILD_DIR}/benchmarks/mma
