name: test
on:
  push:
jobs:
  test-gpu:
    runs-on: [slurm]
    strategy:
      matrix:
        include:
          - name: NVIDIA V100
            partition: cbtq
            gres: gpu:V100
          - name: NVIDIA A4000
            partition: defq
            gres: gpu:A4000
          - name: AMD W7700
            partition: defq
            gres: gpu:W7700
    env:
      DEVICE_NAME: ${{ matrix.name }}
      PARTITION_NAME: ${{ matrix.partition }}
    steps:
      - uses: actions/checkout@v4
      - uses: astron-rd/slurm-action@v1
        with:
          partition: ${{ matrix.partition }}
          gres: ${{ matrix.gres }}
          time: "00:10:00"
          commands: |
            BUILD_DIR=$(mktemp -d -t build-XXXXXXXX)
            if [[ "$PARTITION_NAME" == cbtq ]]; then
              module load spack/d4468dcc
            else
              module load spack/20250403
            fi
            if [[ "$DEVICE_NAME" == NVIDIA* ]]; then
              module load cuda
              cmake_flags=""
              append_path=""
            else
              cmake_flags="-DBUILD_WITH_HIP=1"
              append_path="/opt/rocm/bin"
            fi
            module load cmake
            PATH=$PATH:${append_path} cmake -S . -B ${BUILD_DIR} ${cmake_flags}
            make -C ${BUILD_DIR} -j
            ${BUILD_DIR}/benchmarks/benchmark-fp32
            ${BUILD_DIR}/benchmarks/benchmark-mma
